#!/data/data/com.termux/files/usr/bin/bash
# ============================================================================
#  scripts/setup-cloudflared.sh — one-time Cloudflare Tunnel setup so that
#  api.d4mdev.click permanently points at this phone.
#
#  Steps performed:
#    1. install cloudflared (Termux repo, else the ARM64 static binary)
#    2. `cloudflared tunnel login`            (browser, one time)
#    3. `cloudflared tunnel create <name>`    (name comes from .env)
#    4. DNS route: cloudflared tunnel route dns <name> <hostname>
#    5. write ~/.cloudflared/config.yml
#
#  After this, `npm start` brings the tunnel up together with MariaDB + API.
# ============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
TERMUX_PREFIX="${PREFIX:-/data/data/com.termux/files/usr}"

[ -f "$ENV_FILE" ] || { echo "Missing .env (cp .env.example .env)"; exit 1; }
set -a; # shellcheck disable=SC1090
. "$ENV_FILE"; set +a

PORT="${PORT:-4000}"
TUNNEL_NAME="${CLOUDFLARE_TUNNEL_NAME:-pixgram-api}"
HOSTNAME="${CLOUDFLARE_HOSTNAME:-api.d4mdev.click}"
CF_DIR="$HOME/.cloudflared"
CONFIG_FILE="${CLOUDFLARE_TUNNEL_CONFIG:-$CF_DIR/config.yml}"
mkdir -p "$CF_DIR"

# ---- 1. binary -------------------------------------------------------------
if ! command -v cloudflared >/dev/null 2>&1; then
  echo "[CF] cloudflared missing — trying pkg…"
  if command -v pkg >/dev/null 2>&1 && pkg install -y cloudflared >/dev/null 2>&1; then
    echo "[CF] Installed from the Termux repo."
  else
    echo "[CF] Downloading the ARM64 static binary…"
    curl -fL --retry 3 -o "$TERMUX_PREFIX/bin/cloudflared" \
      https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm64
    chmod +x "$TERMUX_PREFIX/bin/cloudflared"
  fi
fi
cloudflared --version

# ---- 2. login --------------------------------------------------------------
if [ ! -f "$CF_DIR/cert.pem" ]; then
  echo "[CF] Opening the browser for Cloudflare login (choose the d4mdev.click zone)…"
  cloudflared tunnel login
fi

# ---- 3. tunnel -------------------------------------------------------------
if ! cloudflared tunnel list | grep -qE "(^|[[:space:]])${TUNNEL_NAME}([[:space:]]|$)"; then
  echo "[CF] Creating tunnel '$TUNNEL_NAME'"
  cloudflared tunnel create "$TUNNEL_NAME"
fi

TUNNEL_ID="$(cloudflared tunnel list --output json | tr -d '\n' | sed -n "s/.*\"id\":\"\([^\"]*\)\",\"name\":\"${TUNNEL_NAME}\".*/\1/p")"
[ -n "$TUNNEL_ID" ] || { echo "[CF] Could not resolve the tunnel id."; exit 1; }
echo "[CF] Tunnel id: $TUNNEL_ID"

# ---- 4. DNS ----------------------------------------------------------------
echo "[CF] Routing $HOSTNAME → tunnel $TUNNEL_NAME"
cloudflared tunnel route dns "$TUNNEL_NAME" "$HOSTNAME" || true

# ---- 5. config -------------------------------------------------------------
cat > "$CONFIG_FILE" <<YAML
# Generated by scripts/setup-cloudflared.sh — do not commit credentials.
tunnel: ${TUNNEL_ID}
credentials-file: ${CF_DIR}/${TUNNEL_ID}.json
protocol: quic
no-autoupdate: true
loglevel: info
ingress:
  # The API, the /uploads static files AND /admin all live on this one origin.
  - hostname: ${HOSTNAME}
    service: http://127.0.0.1:${PORT}
    originRequest:
      noTLSVerify: true
      connectTimeout: 30s
  - service: http_status:404
YAML

echo "[CF] Wrote $CONFIG_FILE"
echo "[CF] Test with: cloudflared tunnel run $TUNNEL_NAME"
echo "[CF] Then just use: npm start"
